notifications:
  email: false
jobs:
  include:
  - stage: test
    if: branch = master OR type IN (pull_request)
    language: node_js
    node_js: 9
    cache: yarn
    install: yarn install
    script: yarn test
  - stage: build
    if: tag IS present
    language: node_js
    node_js: 9
    cache: yarn
    install: yarn install
    script: yarn build
    before_deploy: tar -zcvf dist.tar.gz build
    deploy:
      provider: releases
      skip_cleanup: true
      api_key:
        secure: M5l0WcmA99PgdR1HJzyJh9b8VXW391qn2m9xfZLTzIr2U3Y19E9mU9uNVPSE1Qumt4KRPLoZz7RUYcTybhLNDEXtCdRQ5gNtKrXWQSoJJgwlG+IPJYJr5fImz4mwdvi8LgrO6xf3I2dDJkmAaM9DAxp3zs04VHjmqFCNliSDNgw1HokHZ9Qt6j0+FZ4FX8LO7TQuOR9JK9su810Pw10j5mCCitxCykkEDrrk/1mFbwwrwpoMECN3yo1TjPWMpRYdOou66qkWxcqyL5+udg9GsBCCxp5hAmc10i+NPHPrI6JNp2QD5sK8wxNM3d71e2+vJP9d4k7djB1Vglta9k+Wtf3ZcBHPIJzI8TudANVtLMYf9qTODJpw4IbARiSLRMCz4uGy0a5oCn7qFFYMn5Rp9gayhhxQmPDLC91rWJidPt2G/2iSPIGIAB8iYeynI1YfYFgnyrLtSixasydHNKw6pzuIvfH6/pqWy7JXH7brcAFwEOaS/dbR1bsXkROTP5J+eEC9GlIOjcmnmcTj/oB6LsfHkYn1p35ibNh/1GV4N5LQYHv4rwfoo70JsrJRvxK3KnOUrWmMU4yWj0dxJToeegxBmkYRW1Q/byLZR7HyOJqyjbiOPifzVWQQ62EgT9CXw/xt4Aqt5P0/knsudsf9hN6JyD5Fb8zeNyQyy3V4zhA=
      file: dist.tar.gz
      on:
        tags: true
    after_deploy: bash .travis/deploy-to-qa.sh
